- name: Create AWS credentials directory 
  file:
    path: "/home/ubuntu/k8s"
    state: directory
    mode: "777"

- name: Copying yaml files
  copy:
    src: /home/mohamedmamdouh/iti-newpart/Graduation_Project/k8s/jenkins/kubernetes-jenkins/
    dest: /home/ubuntu/k8s/
    mode: "644"

- name: enviroment Configuration
  lineinfile:
    path: /home/ubuntu/.bashrc
    line: "alias k='kubectl' "

# - name: Copying deployment script
#   copy:
#     src: /home/mohamedmamdouh/iti-newpart/Graduation_Project/k8s/jenkins/deploy-script.sh
#     dest: /home/ubuntu/k8s/
#     mode: "755" 

# - name: Copying cleaning script
#   copy:
#     src: /home/mohamedmamdouh/iti-newpart/Graduation_Project/k8s/jenkins/delete-script.sh
#     dest: /home/ubuntu/k8s/
#     mode: "755" 

- name: Execute script with using Ansible
  script: 
    cmd: /home/mohamedmamdouh/iti-newpart/Graduation_Project/k8s/jenkins/deploy-script.sh
    chdir: /home/ubuntu/k8s/
  register: script_status

    # interpreter: /bin/bash

# - name: running deployment script
#   # become: "ubuntu"
#   shell: |
#     echo "Done" > /home/ubuntu/start.script
#     bash /home/ubuntu/k8s/deploy-script.sh
#     echo "Done" > /home/ubuntu/done.script
#   register: script

- name: Show bucket details
  debug:
    var: script_status
# - name: kubectl command
#   k8s:
#     name: test dep
#     api_version: v1
#     kind: Namespace
#     state: present
# - name: Create a Deployment by reading the definition from a local file
  

# #   # kubernetes.core.k8s:
# #   #   state: present
# #   #   src: "{{ item }}"
#   # shell: kubectl apply -f "{{ item }}"
#   shell: mkdir "{{ item }}"
# #     # src: "{{/home/ubuntu/k8s/deployment.yml}}"

#   with_items:
#       - /home/ubuntu/1-namespace.yaml
#       - /home/ubuntu/k8s/2-serviceAccount.yaml
#       - /home/ubuntu/k8s/3-volume.yaml
#       - /home/ubuntu/k8s/4-jenkins-dep.yaml
#       - /home/ubuntu/k8s/5-service.yaml
