- name: Configuration of control machine  # play name
  hosts: all  # aliassudo apt install dragonplayer
  # become: true # to use sudo , use root user
  gather_facts: false
  roles:
    # - roles/control-machine
    - roles/deploying-jenkins
