---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: GraduationProject-app
  namespace: app
  labels:
    app: app-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-1-selector
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: app
        image: mohamedmamdouhiv/gp-app:v1.0 
        ports:
        - containerPort: 80


